definitions:
  dto.AdminInfoOutput:
    properties:
      Introduction:
        description: 介绍
        type: string
      avatar:
        description: 头像
        type: string
      id:
        type: integer
      loginTime:
        type: string
      name:
        type: string
      roles:
        description: 角色
        items:
          type: string
        type: array
    type: object
  dto.AdminLoginInput:
    properties:
      password:
        example: 密码
        type: string
      userName:
        example: 用户名
        type: string
    required:
    - password
    - userName
    type: object
  dto.AdminLoginOutput:
    properties:
      token:
        example: token
        type: string
    type: object
  dto.ChangePwdInput:
    properties:
      password:
        example: 密码
        type: string
      userName:
        example: 用户名
        type: string
    required:
    - password
    - userName
    type: object
  dto.DemoInput:
    properties:
      age:
        example: 20
        type: integer
      name:
        example: 姓名
        type: string
      passwd:
        example: "123456"
        type: string
    required:
    - age
    - name
    - passwd
    type: object
  middleware.Response:
    properties:
      data:
        type: object
      errmsg:
        type: string
      errno:
        type: integer
      stack:
        type: object
      trace_id:
        type: object
    type: object
info:
  contact: {}
paths:
  /admin/admin_info:
    get:
      consumes:
      - application/json
      description: 管理员信息接口
      operationId: /admin/admin_info
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AdminInfoOutput'
              type: object
      summary: 管理员信息接口
      tags:
      - 管理员信息接口
  /admin/changepwd:
    post:
      consumes:
      - application/json
      description: 更改管理员密码
      operationId: /admin/changepwd
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ChangePwdInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 更改管理员密码
      tags:
      - 更改管理员密码
  /admin_login/login:
    post:
      consumes:
      - application/json
      description: 管理员登录接口
      operationId: /admin_login/login
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.AdminLoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AdminLoginOutput'
              type: object
      summary: 管理员登录接口
      tags:
      - 管理员登录接口
  /admin_login/logout:
    get:
      consumes:
      - application/json
      description: 管理员退出接口
      operationId: /admin_login/logout
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AdminLoginOutput'
              type: object
      summary: 管理员退出接口
      tags:
      - 管理员退出接口
  /demo/bind:
    post:
      consumes:
      - application/json
      description: 测试数据绑定
      operationId: /demo/bind
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.DemoInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.DemoInput'
              type: object
      summary: 测试数据绑定
      tags:
      - 用户
swagger: "2.0"
